[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Optimizer settings - this is where the magic happens
optimizer = true
optimizer_runs = 10000

# Advanced optimizer details
via_ir = true  # Enable Yul IR pipeline for better optimizations

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
