[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Optimizer settings - this is where the magic happens
optimizer = true
optimizer_runs = 200

# Advanced optimizer details
via_ir = true  # Enable Yul IR pipeline for better optimizations

# File system permissions for deployment scripts
fs_permissions = [
    { access = "read-write", path = "deployments" }
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# RPC endpoints for different networks
[rpc_endpoints]
metis_hyperion_testnet = "https://hyperion-testnet.metisdevops.link"
local = "http://localhost:8545"

# Etherscan API keys and URLs for verification (commented out for deployment)
# [etherscan]
# metis_hyperion_testnet = { key = "${METIS_API_KEY}", url = "https://hyperion-testnet-explorer.metisdevops.link/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
